gpio.mode(8,gpio.INT)
gpio.trig(8, "up", function (level, pulse2) dofile("init_settings.lua")({def = 0}) node.restart()end)
_s = dofile("init_settings.lua")({def = 1})
node.setcpufreq(node.CPU160MHZ)
dofile("init_wifi.lua")(_s)
local mytimer = tmr.create()
mytimer:register(5000, tmr.ALARM_SINGLE, function(t)
  print("Start")
    dofile("init_settings.lua")({run={ext="run"}})
  t:unregister()
end)
mytimer:start()
