gpio.mode(2, gpio.INPUT)
print(gpio.read(2))
_s = dofile("init_settings.lua")({def = gpio.read(2)})
node.setcpufreq(node.CPU160MHZ)
dofile("init_wifi.lua")(_s)
local mytimer = tmr.create()
mytimer:register(5000, tmr.ALARM_SINGLE, function(t)
  print("Start")
    dofile("init_settings.lua")({run={ext="run"}})
  t:unregister()
end)
mytimer:start()
